# Generated by Django 4.2.20 on 2025-07-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Baseline_index",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ts_code", models.CharField(blank=True, max_length=255, null=True)),
                ("trade_date", models.CharField(blank=True, max_length=10, null=True)),
                ("close", models.IntegerField(blank=True, null=True)),
                ("open", models.IntegerField(blank=True, null=True)),
                ("high", models.IntegerField(blank=True, null=True)),
                ("low", models.IntegerField(blank=True, null=True)),
                ("pre_close", models.IntegerField(blank=True, null=True)),
                ("change", models.IntegerField(blank=True, null=True)),
                ("pct_chg", models.IntegerField(blank=True, null=True)),
                ("vol", models.IntegerField(blank=True, null=True)),
                ("amount", models.IntegerField(blank=True, null=True)),
            ],
            options={"db_table": "大盘指数", "managed": False,},
        ),
        migrations.CreateModel(
            name="Baseline_Profit_Loss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_date", models.CharField(blank=True, max_length=10, null=True)),
                ("assets", models.FloatField(blank=True, null=True)),
                ("profit_and_loss", models.FloatField(blank=True, null=True)),
                ("profit_and_loss_ratio", models.FloatField(blank=True, null=True)),
                (
                    "reference_market_capitalization",
                    models.FloatField(blank=True, null=True),
                ),
                ("strategy_id", models.IntegerField(blank=True, null=True)),
                ("user_id", models.IntegerField(blank=True, null=True)),
            ],
            options={"db_table": "大盘盈亏表", "managed": False,},
        ),
        migrations.CreateModel(
            name="Current_shareholding_information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_date", models.CharField(blank=True, max_length=10, null=True)),
                ("st_code", models.CharField(blank=True, max_length=255, null=True)),
                ("st_name", models.CharField(blank=True, max_length=255, null=True)),
                ("number_of_securities", models.IntegerField(blank=True, null=True)),
                ("saleable_quantity", models.IntegerField(blank=True, null=True)),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "profit_and_loss",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "profit_and_loss_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "latest_value",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "current_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("user_id", models.IntegerField(blank=True, null=True)),
                (
                    "strategy_name",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
            ],
            options={"db_table": "new_war_当前持股信息表", "managed": False,},
        ),
        migrations.CreateModel(
            name="Daily_statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_date", models.CharField(blank=True, max_length=10, null=True)),
                ("balance", models.FloatField(blank=True, null=True)),
                ("available", models.FloatField(blank=True, null=True)),
                (
                    "reference_market_capitalization",
                    models.FloatField(blank=True, null=True),
                ),
                ("assets", models.FloatField(blank=True, null=True)),
                ("profit_and_loss", models.FloatField(blank=True, null=True)),
                ("profit_and_loss_ratio", models.FloatField(blank=True, null=True)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                (
                    "strategy_name",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
            ],
            options={"db_table": "new_war_每日统计表", "managed": False,},
        ),
        migrations.CreateModel(
            name="Historical_transaction_information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trade_date", models.CharField(blank=True, max_length=10, null=True)),
                ("st_code", models.CharField(blank=True, max_length=255, null=True)),
                ("st_name", models.CharField(blank=True, max_length=255, null=True)),
                ("trade_type", models.CharField(blank=True, max_length=5, null=True)),
                (
                    "trade_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("number_of_transactions", models.IntegerField(blank=True, null=True)),
                (
                    "turnover",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("user_id", models.IntegerField(blank=True, null=True)),
                (
                    "strategy_name",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
            ],
            options={"db_table": "new_war_历史成交信息表", "managed": False,},
        ),
        migrations.CreateModel(
            name="SaveState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("state_id", models.CharField(max_length=10)),
                ("state_xml", models.CharField(max_length=3000)),
                ("state_name", models.CharField(max_length=30)),
                ("save_time", models.DateTimeField()),
            ],
            options={"db_table": "Save_LegoState", "managed": False,},
        ),
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("strategy_name", models.CharField(max_length=30)),
                ("introduction", models.CharField(max_length=5000)),
                (
                    "buy_policy_list",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "sell_policy_list",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("author", models.CharField(max_length=30)),
                ("fav_nums", models.CharField(blank=True, max_length=10, null=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("star", models.CharField(blank=True, max_length=10, null=True)),
                ("strategy_id", models.IntegerField()),
                ("uid", models.IntegerField(blank=True, null=True)),
            ],
            options={"db_table": "Strategy_Lego", "managed": False,},
        ),
        migrations.CreateModel(
            name="StrategyDynamic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateField(blank=True, null=True)),
                ("fav_nums", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "subscription_nums",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("star", models.CharField(blank=True, max_length=1, null=True)),
                ("star_12345", models.CharField(blank=True, max_length=10, null=True)),
                ("dates", models.CharField(blank=True, max_length=10, null=True)),
                ("year_profit", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={"db_table": "Strategy_Lego_Dynamic", "managed": False,},
        ),
        migrations.CreateModel(
            name="User_Strategy_Configuration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("userID", models.IntegerField(blank=True, null=True)),
                ("strategyName", models.TextField(blank=True, null=True)),
                ("strategyType", models.TextField(blank=True, null=True)),
                ("strategyDescrib", models.TextField(blank=True, null=True)),
                (
                    "Annual_rate_of_return",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "max_draw_back",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("start_date", models.TextField(blank=True, null=True)),
                ("end_date", models.TextField(blank=True, null=True)),
                (
                    "init_fund",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("income_base", models.TextField(blank=True, null=True)),
                ("sector", models.TextField(blank=True, null=True)),
                ("exp", models.TextField(blank=True, null=True)),
                ("indus", models.TextField(blank=True, null=True)),
                ("remove_st_stock", models.BooleanField(blank=True, null=True)),
                ("remove_suspended_stok", models.BooleanField(blank=True, null=True)),
                (
                    "min_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "max_price",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("optionfactor", models.TextField(blank=True, null=True)),
                ("factor", models.TextField(blank=True, null=True)),
                ("bottomfactor", models.TextField(blank=True, null=True)),
                ("max_hold_num", models.IntegerField(blank=True, null=True)),
                (
                    "total_rate_of_return",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "return_volatility",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                (
                    "sharp_ratio",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=15, null=True
                    ),
                ),
                ("fg", models.TextField(blank=True, null=True)),
            ],
            options={"db_table": "用户策略配置表", "managed": False,},
        ),
    ]
