# Generated by Django 5.2.12 on 2026-04-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("strategy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Industry_Daily_Info",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("st_code", models.CharField(blank=True, max_length=255, null=True)),
                ("Industry_name", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "仅当日行业表",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Stock_Basic_Info",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("st_code", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("list_date", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "股票基本信息remove",
                "managed": False,
            },
        ),
    ]
