# Generated by Django 5.2.12 on 2026-04-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name="StockBasicInfo",
            fields=[
                ("st_code", models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name="股票代码")),
                ("symbol", models.CharField(blank=True, max_length=20, null=True, verbose_name="股票代码(不含后缀)")),
                ("name", models.CharField(max_length=50, verbose_name="股票名称")),
                ("area", models.CharField(blank=True, max_length=50, null=True, verbose_name="地区")),
                ("industry", models.CharField(blank=True, max_length=100, null=True, verbose_name="行业")),
                ("fullname", models.CharField(blank=True, max_length=100, null=True, verbose_name="股票全称")),
                ("enname", models.CharField(blank=True, max_length=200, null=True, verbose_name="英文名称")),
                ("market", models.CharField(blank=True, max_length=20, null=True, verbose_name="市场类型")),
                ("list_status", models.CharField(blank=True, max_length=10, null=True, verbose_name="上市状态")),
                ("list_date", models.CharField(blank=True, max_length=10, null=True, verbose_name="上市日期")),
                ("delist_date", models.CharField(blank=True, max_length=10, null=True, verbose_name="退市日期")),
            ],
            options={
                "verbose_name": "股票基本信息",
                "verbose_name_plural": "股票基本信息",
                "db_table": "股票基本信息remove",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StockDailyData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("st_code", models.CharField(max_length=20, verbose_name="股票代码")),
                ("trade_date", models.CharField(max_length=10, verbose_name="交易日期")),
                ("open", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="开盘价")),
                ("high", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="最高价")),
                ("low", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="最低价")),
                ("close", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="收盘价")),
                ("vol", models.BigIntegerField(verbose_name="成交量")),
                ("pre_close", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="前收盘价")),
                ("pct_chg", models.DecimalField(decimal_places=4, max_digits=10, verbose_name="涨跌幅")),
                ("rsv", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="RSV")),
                ("kdj_k", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="KDJ_K")),
                ("kdj_d", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="KDJ_D")),
                ("kdj_j", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="KDJ_J")),
                ("ema26", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="EMA26")),
                ("ema12", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="EMA12")),
                ("macd_dif", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="MACD_DIF")),
                ("macd_dea", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="MACD_DEA")),
                ("macd_macd", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="MACD_MACD")),
                ("wr_wr1", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="WR1")),
                ("wr_wr2", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="WR2")),
                ("boll_boll", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="BOLL")),
                ("boll_ub", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="BOLL上轨")),
                ("boll_lb", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="BOLL下轨")),
                ("cci", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="CCI")),
                ("week_ema_short", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="周线短期EMA")),
                ("week_ema_long", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="周线长期EMA")),
                ("week_macd_dif", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="周线MACD_DIF")),
                ("week_macd_dea", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="周线MACD_DEA")),
                ("week_macd_macd", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="周线MACD")),
                ("lastweek_macd_dif", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="上周MACD_DIF")),
                ("lastlastweek_macd_dif", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="上上周MACD_DIF")),
                ("lastweek_macd_macd", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="上周MACD")),
                ("lastlastweek_macd_macd", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="上上周MACD")),
                ("TYP", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="TYP")),
                ("ma_TYP_14", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="14日移动平均")),
                ("AVEDEV", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="AVEDEV")),
                ("last_dif", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="last_dif")),
                ("pre_macd_macd", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="前MACD")),
                ("pre_pre_macd_macd", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="前前MACD")),
                ("pre_cci", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="前CCI")),
                ("close_max_20", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="20日最高价")),
                ("macd_max_20", models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name="20日MACD最大值")),
            ],
            options={
                "verbose_name": "股票日线数据",
                "verbose_name_plural": "股票日线数据",
                "db_table": "partition_table",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="StockDiagnosisResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("st_code", models.CharField(max_length=20, verbose_name="股票代码")),
                ("diagnosis_date", models.DateField(auto_now_add=True, verbose_name="诊断日期")),
                ("technical_score", models.IntegerField(help_text="0-100分", verbose_name="技术面评分")),
                ("technical_analysis", models.TextField(verbose_name="技术面分析")),
                ("fundamental_score", models.IntegerField(help_text="0-100分", verbose_name="基本面评分")),
                ("fundamental_analysis", models.TextField(verbose_name="基本面分析")),
                ("overall_score", models.IntegerField(help_text="0-100分", verbose_name="综合评分")),
                ("overall_analysis", models.TextField(verbose_name="综合分析")),
                ("recommendation", models.CharField(choices=[("buy", "买入"), ("hold", "持有"), ("sell", "卖出")], max_length=20, verbose_name="投资建议")),
                ("risk_level", models.CharField(choices=[("low", "低风险"), ("medium", "中等风险"), ("high", "高风险")], max_length=20, verbose_name="风险等级")),
                ("risk_factors", models.TextField(verbose_name="风险因素")),
            ],
            options={
                "verbose_name": "股票诊断结果",
                "verbose_name_plural": "股票诊断结果",
                "db_table": "stock_diagnosis_result",
                "managed": True,
            },
        ),
    ]
