# Generated by Django 5.2.12 on 2026-04-04 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="usersubscription",
            options={"managed": False},
        ),
    ]
