# Generated by Django 5.2.12 on 2026-04-04 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_user_options_alter_usersubscription_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="user_user",
        ),
        migrations.AlterModelTable(
            name="usersubscription",
            table="user_usersubscription",
        ),
    ]
