# Generated by Django 5.2.12 on 2026-04-16 12:00

from django.db import migrations, models


DEFAULT_ADMIN_USERNUMBER = "admin"
DEFAULT_ADMIN_PASSWORD = "admin"
DEFAULT_ADMIN_NAME = "系统管理员"


def ensure_default_admin(apps, schema_editor):
    User = apps.get_model("user", "User")

    user = User.objects.filter(usernumber=DEFAULT_ADMIN_USERNUMBER).first()
    if user is None:
        User.objects.create(
            usernumber=DEFAULT_ADMIN_USERNUMBER,
            password=DEFAULT_ADMIN_PASSWORD,
            name=DEFAULT_ADMIN_NAME,
            membership_level="admin",
            membership_expiry=None,
        )
        return

    updated = False
    if user.membership_level != "admin":
        user.membership_level = "admin"
        updated = True
    if user.membership_expiry is not None:
        user.membership_expiry = None
        updated = True
    if not user.name:
        user.name = DEFAULT_ADMIN_NAME
        updated = True

    if updated:
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_table_alter_usersubscription_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="membership_level",
            field=models.CharField(
                choices=[
                    ("free", "免费用户"),
                    ("basic", "基础会员"),
                    ("premium", "高级会员"),
                    ("vip", "VIP会员"),
                    ("admin", "管理员"),
                ],
                default="free",
                max_length=20,
            ),
        ),
        migrations.RunPython(ensure_default_admin, migrations.RunPython.noop),
    ]
